### ISSUE TITLE
artifacts created by IIIF?

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#50] opened 2015-07-07 21:58 UTC
I've noticed some artifacts on tiles on this image:

![screen shot 2015-07-07 at 23 55 37](https://cloud.githubusercontent.com/assets/5627431/8558348/ca3e9458-2503-11e5-932e-dc25019f1e31.png)

which disappear when zoomed in further.

![screen shot 2015-07-07 at 23 57 08](https://cloud.githubusercontent.com/assets/5627431/8558364/ee5b6a78-2503-11e5-8dd2-54e44cd9c969.png)

Do/Can we do anything about/prevent that?

**Comment by o1da** [comment] 2015-07-08 10:06
Yes it looks like a problem on the IIIF side. If you look at full size image on `http://iiif.embedr.eu/Canaletto_I_058_jpg/full/full/0/native.jpg` it is without artefacts.
@MartinMikita please look at this problem.

**Comment by MartinMikita** [comment] 2015-07-08 19:04
Problem is in the viewer.

Viewer is requesting wrong type of URL for "side-tiles"
actual requested URL:
http://iiif.embedr.eu/Canaletto_I_058_jpg/4608,512,94,512/47,/0/default.jpg
correct requested URL:
http://iiif.embedr.eu/Canaletto_I_058_jpg/4608,512,94,512/47,256/0/default.jpg

side-tiles has size 47 x 256 - otherwise they are reduced on server using bilinear interpolation into 47x47 pixels, and then on the client resized back to 47x256.

Better solution is using percentage as size from region (if region is calculated correctly)
http://iiif.embedr.eu/Canaletto_I_058_jpg/4608,512,94,512/pct:50/0/default.jpg

**Comment by klokan** [comment] 2015-07-08 20:02
In #28 I have suggested upgrade of the OpenSeaDragon component to 2.0. It may help to solve this problem and also some others - such as Retina support, etc.
That task has NOT been assigned to @klokantech team - but to a third-party... @mzeinstra - please inform your front-end developer...

@MartinMikita - could you please create an internal ticket for tracking the here reported issue on iiifserver-build repo. The request http://iiif.embedr.eu/Canaletto_I_058_jpg/4608,512,94,512/47,/0/default.jpg should not contain artefacts in the lower part of the returned image. It is probably a bug in stable IIPImage in the ruven's code - which we may fix (but we are probably not obligated by the HAWK contract to do that).

**Comment by mzeinstra** [comment] 2015-07-08 21:18
Yes, completely agree that this is not part of our development within Hawk and frankly i suspected this was due to one of the open source projects we were doing, I was just making sure.

**Comment by klokan** [comment] 2015-07-08 21:20
Related internal private ticket created at: https://github.com/klokan/iiifserver-build/issues/20

**Comment by klokan** [comment] 2015-07-08 21:22
@o1da could you please provide us with a download link for the related .jp2 file? To be able to reproduce the bug easily?

**Comment by o1da** [comment] 2015-07-08 21:44
https://drive.google.com/file/d/0B2VmXf-_xLa6VHE3SlZvSnQtQ1U/view

**Closed as completed** 2015-07-09 18:09 UTC
Labels: enhancement
